services:
  app:
    build:
      context: .
      target: dev
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - web_network
    environment:
      - CI=true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm_store:/pnpm/store
      - next_cache:/app/.next
    command: >
      sh -c "pnpm install && pnpm run dev"
    develop:
      watch:
        - path: package.json
          action: rebuild
        - path: pnpm-lock.yaml
          action: rebuild
        - path: .
          target: /app
          action: sync

volumes:
  node_modules:
  pnpm_store:
  next_cache:

networks:
  web_network:
    external: true
