services:
  app:
    build:
      context: .
      target: dev
    platform: linux/amd64
    env_file:
      - .env
    ports:
      - "${APP_PORT:-3000}:3000"
    networks:
      - web_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
networks:
  web_network:
    external: true
