import '@mantine/core/styles.css';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import { cookies } from 'next/headers';
/**
 * Internal dependency
 */
import './globals.css';
import { projectData } from '@/constants';
import StoreProvider from '@/components/store-provider';
import ToasterProvider from '@/components/toaster-provider';
import ValueProvider from '@/components/value-provider';
import { theme } from '@/app/lib/theme';

export const metadata: Metadata = {
    title: `${projectData.title} - Professional Haircuts & Shaves in New York`,
    description: 'Generated by create next app',
};

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const accessToken = cookieStore.get('access_token')?.value || '';

    return (
        <html lang="en" {...mantineHtmlProps}>
            <head>
                <ColorSchemeScript />
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <StoreProvider>
                    <MantineProvider theme={theme}>
                        <ToasterProvider />
                        <ValueProvider accessToken={accessToken} />
                        {children}
                    </MantineProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
